spring.application.name=CurryRecipeManager

# DataSource
spring.datasource.url=jdbc:h2:file:./data/curry_recipe_manager_db
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# SQL Init
spring.sql.init.mode=never
spring.sql.init.schema-locations=classpath:schema.sql
spring.sql.init.data-locations=classpath:data.sql

# H2DB
spring.h2.console.enabled=true
spring.h2.console.settings.web-allow-others=false

#MyBatis
mybatis.mapper-locations=classpath*:/mapper/*.xml

#message
spring.messages.basename=message/ValidationMessages
