/** ==========================================
 * 無水カレー管理システム
 * テーブル定義
 * ========================================== */

/** レシピテーブル */
CREATE TABLE IF NOT EXISTS recipe (
    /** ID */
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    /** レシピ名 */
    recipe_name VARCHAR(100) NOT NULL,
    /** 調理時間（分） */
    cooking_time INTEGER NOT NULL,
    /** 自己評価（1～5） */
    evaluation INTEGER CHECK (evaluation BETWEEN 1 AND 5),
    /** 登録日時 */
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, 
	/** 更新日時 */
    updated_at TIMESTAMP,
    /** 主キー */
    PRIMARY KEY (id)
);


/** 材料テーブル */
CREATE TABLE IF NOT EXISTS ingredient (
    /** ID */
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    /** レシピID */
    recipe_id BIGINT NOT NULL,
    /** 材料名 */
    ingredient_name VARCHAR(100) NOT NULL,
    /** 分量 */
    amount VARCHAR(20) NOT NULL,
    /** 単位 */
	unit VARCHAR(3) NOT NULL, 
	/** 主キー */
    PRIMARY KEY (id),
    /** 外部キー */
    CONSTRAINT fk_ingredient_recipe
        FOREIGN KEY (recipe_id)
        REFERENCES recipe(id)
        ON DELETE CASCADE
);


/** 調理手順テーブル */
CREATE TABLE IF NOT EXISTS recipe_step (
    /** ID */
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    /** レシピID */
    recipe_id BIGINT NOT NULL,
    /** 手順番号 */
    step_no INTEGER NOT NULL,
    /** 手順内容 */
    content VARCHAR(500) NOT NULL,
    /** 主キー */
    PRIMARY KEY (id),
    /** 外部キー */
    CONSTRAINT fk_recipe_step_recipe
        FOREIGN KEY (recipe_id)
        REFERENCES recipe(id)
        ON DELETE CASCADE
);


/** 調理結果テーブル */
CREATE TABLE IF NOT EXISTS cooking_result (
    /** ID */
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    /** レシピID */
    recipe_id BIGINT NOT NULL,
    /** 調理日付 */
    cooked_date DATE NOT NULL,
    /** 自己評価（1～5） */
    score INTEGER CHECK (score BETWEEN 1 AND 5),
    /** 一口メモ */
    memo VARCHAR(500),
    /** 主キー */
    PRIMARY KEY (id),
    /** 外部キー */
    CONSTRAINT fk_cooking_result_recipe
        FOREIGN KEY (recipe_id)
        REFERENCES recipe(id)
        ON DELETE CASCADE
);